[build]
  # This is the directory to change to before starting a build.
  base = "/"
  # For monorepos, the directory that contains your site files, including the netlify.toml. Set this value only if it is different from the base directory.
  package = "apps/web"
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "apps/web/build"
  # This will be your default build command
  command = "cd apps/web && pnpm run envsetup && cd ../../ && pnpm run build:web --skip-nx-cache"

[context.deploy-preview]
  command = "cd apps/web && pnpm run envsetup && pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    Permissions-Policy = "accelerometer=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), interest-cohort=()"
    Strict-Transport-Security = '''
    max-age=63072000;
    includeSubDomains;
    preload'''
