packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/*'
  - 'apps/*'
  - 'libs/*'
  # exclude packages that are inside test directories
  - '!**/test/**'
  # all packages in enterprise modules
  - 'enterprise/packages/*'
  # playground apps
  - 'playground/*'
