name: 'Notify Slack on workflow failure'
runs:
  using: "composite"
  steps:
    - name: Notify Slack Action
      uses: ravsamhq/notify-slack-action@v2
      if: ${{ always() && github.ref_name == 'next' || github.ref_name == 'main' || github.ref_name == 'prod' }}
      with:
        footer: "Run: {run_url}\nCommit: {commit_url}"
        message_format: "{emoji} *{workflow}* {status_message} in <{repo_url}|{repo}>"
        notification_title: "{workflow} is now failing!"
        notify_when: "failure"
        status: "failure"
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_ENG_FEED_GITHUB }}
